[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = []

[start]
cmd = "cd php-app/public && php -S 0.0.0.0:$PORT index.php"
