[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
  "ls -la",
  "pwd",
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts",
  "ls -la vendor"
]

[phases.build]
cmds = []

[start]
cmd = "php -S 0.0.0.0:$PORT -t php-app/public"
