[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "cd php-app/public && php -S 0.0.0.0:$PORT index.php"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
nixPkgs = ["php82", "php82Packages.composer"]
